language: c++

dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
        packages:
            - g++-7
            - clang-4.0

compiler:
    - gcc
  # - clang

install:
    # Prepare compiler
    - if [ "$CXX" = "g++" ];     then export CXX="g++-7"       CC="gcc-7";     fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.0" CC="clang-4.0"; fi

script:
    - make
